kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: azure-disk-node-privileged-binding
subjects:
  - kind: ServiceAccount
    name: azure-disk-csi-driver-node-sa
    namespace: openshift-azure-disk-csi-driver
roleRef:
  kind: ClusterRole
  name: azure-disk-privileged-role
  apiGroup: rbac.authorization.k8s.io
