kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: openstack-cinder-csi-snapshotter-binding
subjects:
  - kind: ServiceAccount
    name: openstack-cinder-csi-driver-controller-sa
    namespace: openshift-openstack-cinder-csi-driver
roleRef:
  kind: ClusterRole
  name: openstack-cinder-external-snapshotter-role
  apiGroup: rbac.authorization.k8s.io
