// +build !ignore_autogenerated

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenStackCinderDriver) DeepCopyInto(out *OpenStackCinderDriver) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenStackCinderDriver.
func (in *OpenStackCinderDriver) DeepCopy() *OpenStackCinderDriver {
	if in == nil {
		return nil
	}
	out := new(OpenStackCinderDriver)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OpenStackCinderDriver) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenStackCinderDriverList) DeepCopyInto(out *OpenStackCinderDriverList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OpenStackCinderDriver, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenStackCinderDriverList.
func (in *OpenStackCinderDriverList) DeepCopy() *OpenStackCinderDriverList {
	if in == nil {
		return nil
	}
	out := new(OpenStackCinderDriverList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OpenStackCinderDriverList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenStackCinderDriverSpec) DeepCopyInto(out *OpenStackCinderDriverSpec) {
	*out = *in
	in.OperatorSpec.DeepCopyInto(&out.OperatorSpec)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenStackCinderDriverSpec.
func (in *OpenStackCinderDriverSpec) DeepCopy() *OpenStackCinderDriverSpec {
	if in == nil {
		return nil
	}
	out := new(OpenStackCinderDriverSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenStackCinderDriverStatus) DeepCopyInto(out *OpenStackCinderDriverStatus) {
	*out = *in
	in.OperatorStatus.DeepCopyInto(&out.OperatorStatus)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenStackCinderDriverStatus.
func (in *OpenStackCinderDriverStatus) DeepCopy() *OpenStackCinderDriverStatus {
	if in == nil {
		return nil
	}
	out := new(OpenStackCinderDriverStatus)
	in.DeepCopyInto(out)
	return out
}
