kind: Deployment
apiVersion: apps/v1
metadata:
  name: azure-disk-csi-driver-controller
  namespace: openshift-azure-disk-csi-driver
spec:
  selector:
    matchLabels:
      app: azure-disk-csi-driver-controller
  serviceName: azure-disk-csi-driver-controller
  replicas: 1
  template:
    metadata:
      labels:
        app: azure-disk-csi-driver-controller
    spec:
      hostNetwork: true
      serviceAccount: azure-disk-csi-driver-controller-sa
      priorityClassName: system-cluster-critical
      tolerations:
        - key: CriticalAddonsOnly
          operator: Exists
      containers:
        - name: csi-driver
          image: mcr.microsoft.com/k8s/csi/azuredisk-csi:latest
          args:
            - "--v=5"
            - "--endpoint=$(CSI_ENDPOINT)"
          ports:
            - containerPort: 29602
              name: healthz
              protocol: TCP
            - containerPort: 29604
              name: metrics
              protocol: TCP
          livenessProbe:
            failureThreshold: 5
            httpGet:
              path: /healthz
              port: healthz
            initialDelaySeconds: 30
            timeoutSeconds: 10
            periodSeconds: 30
          env:
            - name: AZURE_CREDENTIAL_FILE
              valueFrom:
                configMapKeyRef:
                  name: azure-cred-file
                  key: path
                  optional: true
            - name: CSI_ENDPOINT
              value: unix:///csi/csi.sock
          volumeMounts:
            - mountPath: /csi
              name: socket-dir
            - mountPath: /etc/kubernetes/
              name: azure-cred
            - mountPath: /var/lib/waagent/ManagedIdentity-Settings
              readOnly: true
              name: msi
          resources:
            limits:
              cpu: 1
              memory: 1Gi
            requests:
              cpu: 10m
              memory: 20Mi
        - name: csi-provisioner
          image: mcr.microsoft.com/oss/kubernetes-csi/csi-provisioner:v1.5.0
          args:
            - "--feature-gates=Topology=true"
            - "--csi-address=$(ADDRESS)"
            - "--v=5"
            - "--timeout=120s"
            - "--enable-leader-election"
            - "--leader-election-type=leases"
          env:
            - name: ADDRESS
              value: /csi/csi.sock
          volumeMounts:
            - mountPath: /csi
              name: socket-dir
          resources:
            limits:
              cpu: 1
              memory: 1Gi
            requests:
              cpu: 10m
              memory: 20Mi
        - name: csi-attacher
          image: mcr.microsoft.com/oss/kubernetes-csi/csi-attacher:v2.2.0
          args:
            - "-v=5"
            - "-csi-address=$(ADDRESS)"
            - "-timeout=120s"
            - "-leader-election"
          env:
            - name: ADDRESS
              value: /csi/csi.sock
          volumeMounts:
            - mountPath: /csi
              name: socket-dir
          resources:
            limits:
              cpu: 1
              memory: 1Gi
            requests:
              cpu: 10m
              memory: 20Mi
        - name: csi-resizer
          image: mcr.microsoft.com/oss/kubernetes-csi/csi-resizer:v0.3.0
          args:
            - "-csi-address=$(ADDRESS)"
            - "-v=5"
            - "-leader-election"
          env:
            - name: ADDRESS
              value: /csi/csi.sock
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
          resources:
            limits:
              cpu: 1
              memory: 1Gi
            requests:
              cpu: 10m
              memory: 20Mi
        - name: csi-snapshotter
          image: mcr.microsoft.com/oss/kubernetes-csi/csi-snapshotter:v2.0.1
          args:
            - "-csi-address=$(ADDRESS)"
            - "-leader-election"
            - "--v=5"
          env:
            - name: ADDRESS
              value: /csi/csi.sock
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
          resources:
            limits:
              cpu: 1
              memory: 1Gi
            requests:
              cpu: 10m
              memory: 20Mi
        # - name: liveness-probe
        #   image: mcr.microsoft.com/oss/kubernetes-csi/livenessprobe:v1.1.0
        #   args:
        #     - --csi-address=/csi/csi.sock
        #     - --connection-timeout=3s
        #     - --health-port=29602
        #     - --v=5
        #   volumeMounts:
        #     - name: socket-dir
        #       mountPath: /csi
        #   resources:
        #     limits:
        #       cpu: 1
        #       memory: 1Gi
        #     requests:
        #       cpu: 10m
        #       memory: 20Mi
      volumes:
        - name: socket-dir
          emptyDir: {}
        - name: azure-cred
          hostPath:
            path: /etc/kubernetes/
            type: Directory
        - name: msi
          hostPath:
            path: /var/lib/waagent/ManagedIdentity-Settings
