apiVersion: cloudcredential.openshift.io/v1
kind: CredentialsRequest
metadata:
  name: openshift-openstack-cinder-csi-driver
  namespace: openshift-cloud-credential-operator
spec:
  secretRef:
    name: openstack-cloud-credentials
    namespace: openshift-openstack-cinder-csi-driver
  providerSpec:
    apiVersion: cloudcredential.openshift.io/v1
    kind: OpenStackProviderSpec
